insert into city_weather (postal_code, weather, name, state_code, country) values ('00501','35','HOLTSVILLE','NY','SUFFOLK');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00544','35','HOLTSVILLE','NY','SUFFOLK');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00601','32','ADJUNTAS','PR','ADJUNTAS');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00602','33','AGUADA','PR','AGUADA');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00603','27','AGUADILLA','PR','AGUADILLA');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00604','26','AGUADILLA','PR','AGUADILLA');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00605','41','AGUADILLA','PR','AGUADILLA');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00606','23','MARICAO','PR','MARICAO');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00610','30','ANASCO','PR','ANASCO');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00611','33','ANGELES','PR','UTUADO');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00612','22','ARECIBO','PR','ARECIBO');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00613','21','ARECIBO','PR','ARECIBO');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00614','26','ARECIBO','PR','ARECIBO');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00616','24','BAJADERO','PR','ARECIBO');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00617','21','BARCELONETA','PR','BARCELONETA');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00622','41','BOQUERON','PR','CABO ROJO');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00623','17','CABO ROJO','PR','CABO ROJO');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00624','19','PENUELAS','PR','PENUELAS');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00627','18','CAMUY','PR','CAMUY');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00631','22','CASTANER','PR','LARES');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00636','21','ROSARIO','PR','SAN GERMAN');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00637','23','SABANA GRANDE','PR','SABANA GRANDE');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00638','24','CIALES','PR','CIALES');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00641','28','UTUADO','PR','UTUADO');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00646','31','DORADO','PR','DORADO');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00647','34','ENSENADA','PR','GUANICA');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00650','38','FLORIDA','PR','FLORIDA');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00652','39','GARROCHALES','PR','ARECIBO');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00653','22','GUANICA','PR','GUANICA');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00656','23','GUAYANILLA','PR','GUAYANILLA');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00659','35','HATILLO','PR','HATILLO');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00660','38','HORMIGUEROS','PR','HORMIGUEROS');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00662','37','ISABELA','PR','ISABELA');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00664','38','JAYUYA','PR','JAYUYA');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00667','33','LAJAS','PR','LAJAS');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00669','31','LARES','PR','LARES');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00670','35','LAS MARIAS','PR','LAS MARIAS');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00674','37','MANATI','PR','MANATI');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00676','33','MOCA','PR','MOCA');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00677','38','RINCON','PR','RINCON');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00678','32','QUEBRADILLAS','PR','QUEBRADILLAS');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00680','23','MAYAGUEZ','PR','MAYAGUEZ');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00681','27','MAYAGUEZ','PR','MAYAGUEZ');
insert into city_weather (postal_code, weather, name, state_code, country) values ('00682','28','MAYAGUEZ','PR','MAYAGUEZ');